services:
  web:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "8080:80"
    environment:
      # - NGINX_HOST=foobar.com
      - NGINX_PORT=80