log_format json_combined escape=json
    '{'
        '"time_local": "$time_local",'
        '"remote_addr": "$remote_addr",'
        '"request": "$request",'
        '"status": "$status",'
        '"body_bytes_sent": "$body_bytes_sent",'
        '"http_referer": "$http_referer",'
        '"http_user_agent": "$http_user_agent",'
        '"http_x_forwarded_for": "$http_x_forwarded_for"'
    '}';

  server {
    listen 80;
    # access_log syslog:server=elasticsearch:9200 json_combined;

    # Vue3 前端
    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
    }

    location /web {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
    }

    # API 反向代理
    location /api/ {
      proxy_pass http://koa-server:3000/;
    }

    # 图片服务代理
    # location /images {
    #   proxy_pass http://chevereto:80;
    # }

    # Kibana 代理
    # location /kibana {
    #   proxy_pass http://kibana:5601;
    #   proxy_set_header Host $host;
    #   proxy_set_header X-Real-IP $remote_addr;
    #    rewrite ^/kibana/(.*)$ /$1 break;
    # }

 
    location /log {
        access_by_lua_block {
            local http = require "resty.http"
            local httpc = http.new()
            local res, err = httpc:request_uri("http://elasticsearch:9200/nginx/_doc", {
                method = "POST",
                body = ngx.var.request_body,
                headers = { ["Content-Type"] = "application/json" }
            })
        }
    }

  }