# https://hub.docker.com/r/openresty/openresty
# https://github.com/openresty/docker-openresty
# openresty 最佳实践： https://moonbingbing.gitbooks.io/openresty-best-practices/content/


services:
  openresty:
    image: openresty/openresty:alpine
    restart: always
    ports:
      - 80:80
    # networks:
    #   - network1
    volumes:
      - ./conf.d:/etc/nginx/conf.d # 本地:镜像
      - ./nginx.conf:/etc/nginx/nginx.conf # 本地:镜像
      - ./lua_script:/usr/local/openresty/lua_script # 本地:镜像
      - ./html:/usr/local/openresty/nginx/html # 本地:镜像

    # 健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

networks:
  network1:
    name: my-openresty-network
    external: true