# https://hub.docker.com/_/mysql

services:
  my-sql:
    image: mysql:latest
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor123
    # volumes:
    #   - ./data:/etc/data # 本地:镜像
    #   - ./conf:/etc/mysql/conf.d # 本地:镜像